[package]
name = "qrterm"
version = "0.1.0"
authors = ["Nicholas Rodrigues Lordello <nlordell@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.33"
structopt = "0.3.20"
qrcode = "0.12.0"
